# Generated by Django 2.2.12 on 2020-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200504_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderregister',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='orderitemsregister',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
