# Generated by Django 2.2.12 on 2020-05-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200504_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderregister',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderregister',
            name='discount_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
