# Generated by Django 2.2.12 on 2020-05-05 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0004_auto_20200505_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnCnRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=20)),
                ('truck_type', models.CharField(max_length=20)),
                ('truck_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('truck_plate_num', models.CharField(max_length=20)),
                ('remarks', models.CharField(max_length=200)),
                ('order_register', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.OrderRegister')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
