# Generated by Django 2.2.12 on 2020-05-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200512_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dncnregister',
            name='order_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderRegister'),
        ),
        migrations.AlterField(
            model_name='dncnregister',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dncnregister',
            name='type',
            field=models.CharField(choices=[('DN', 'Delivery Note'), ('CN', 'Collection Note')], max_length=20),
        ),
    ]
