# Generated by Django 2.2.12 on 2020-05-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rentaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='returned_date',
            field=models.DateField(null=True),
        ),
    ]
