# Generated by Django 2.2.12 on 2020-05-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200513_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='order_register',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.OrderRegister'),
        ),
    ]
