# Generated by Django 2.2.12 on 2020-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200513_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldetails',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
