# Generated by Django 2.2.12 on 2020-05-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200514_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderregister',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('APPROVED', 'APPROVED'), ('CONFIRMED', 'CONFIRMED'), ('PACKING', 'PACKING'), ('SHIPPED', 'SHIPPED'), ('RECEIVED', 'RECEIVED'), ('CLOSED', 'CLOSED'), ('PURCHASED', 'PURCHASED')], default='ORDERED', max_length=20),
        ),
    ]
